[project]
name = "forecasting-competition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.1",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.4",
]
